version: "3.9"

services:

  api01: &api
    image: makersweb/makerspay:latest
    hostname: api01
    platform: linux/amd64
    restart: on-failure
    environment:
      - DB_HOSTNAME=db
      - PORT=20000
      - JVM_XMS=110m
      - JVM_XMX=110m
      - CONTAINER_MEMORY=234m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=5m
      - MIN_HEAP_FREE_RATIO=30
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=2
      - MAX_POOL_CONNECTION=4
      - LOG_LEVEL=INFO
    ports:
      - "3001:20000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "234MB"
    networks:
      - default

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=20000
      - JVM_XMS=110m
      - JVM_XMX=110m
      - CONTAINER_MEMORY=234m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=5m
      - MIN_HEAP_FREE_RATIO=30
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=2
      - MAX_POOL_CONNECTION=4
      - LOG_LEVEL=INFO
    ports:
      - "3002:20000"
    networks:
      - default

  nginx:
    image: nginx:latest
    restart: on-failure
    container_name: loadbalancer
    platform: linux/amd64
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"
    networks:
      - default

  db:
    image: postgres:16.3-bullseye
    container_name: db
    hostname: db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/data/rinhadb:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "rinhadb"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "140MB"
    networks:
      - default

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
